orders/urls.py
from django.urls import path

from orders.views import (CanceledTemplateView, OrderCreateView,
                          OrderDetailView, OrderListView, SuccessTemplateView, main, mytasks, board, calender, anna,
                          listing, download_file)

app_name = 'orders'

urlpatterns = [
    path('order-create/', OrderCreateView.as_view(), name='order_create'),
    path('', OrderListView.as_view(), name='orders_list'),
    path('order/<int:pk>/', OrderDetailView.as_view(), name='order'),
    path('order-success/',
         SuccessTemplateView.as_view(),
         name='order_success'),
    path('order-canceled/',
         CanceledTemplateView.as_view(),
         name='order_canceled'),

    path('main/', main, name="main"),
    path('my-tasks/', mytasks, name="my-tasks"),
    path('board/', board, name="board"),
    path('upload/', download_file, name="upload"),
    path('calender', calender, name="calender"),
    path('list/', listing, name="list"),
    # path('add-task/', AddTask.as_view(), name='add-task')

    path('anna/', anna, name="anna")

]

store/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from orders.views import stripe_webhook_view
from products.views import IndexView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),
    path('products/', include('products.urls', namespace='products')),
    path('users/', include('users.urls', namespace='users')),
    path('accounts/', include('allauth.urls')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('webhook/stripe/', stripe_webhook_view, name='stripe_webhook'),

    path('', include('django.contrib.auth.urls')),
]


if settings.DEBUG:
    urlpatterns.append(path('__debug__/', include('debug_toolbar.urls')))
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
import django
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LogoutView, PasswordResetConfirmView
from django.urls import path

from users.views import (EmailVerificationView, UserLoginView, UserProfileView,
                         UserRegistrationView, PassResetView, PassDoneView,
                         PassConfirmView, reset_password_message)

app_name = 'users'

urlpatterns = [
    path('login/', UserLoginView.as_view(), name='login'),
    path('registration/', UserRegistrationView.as_view(), name='registration'),
    path('profile/<int:pk>/', login_required(UserProfileView.as_view()), name='profile'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('verify/<str:email>/<uuid:code>/', EmailVerificationView.as_view(), name='email_verification'),

    url(r'^password-reset/$', reset_password_message, name='password_reset'),
    url(r'^password-reset/done/$', PassDoneView.as_view(), name='password_reset_done'),
    # url(r'^password-reset/confirm/(?P<uidb64>[-\w]+)/(?P<token>[-\w]+)/$', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    url(r'^password-reset/complete/$', django.contrib.auth.views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

orders/models.py
from datetime import date

from django.db import models

from products.models import Basket
from users.models import User


class Order(models.Model):
    CREATED = 0
    PAID = 1
    ON_WAY = 2
    DELIVERED = 3
    STATUSES = (
        (CREATED, 'Создан'),
        (PAID, 'Оплачен'),
        (ON_WAY, 'В пути'),
        (DELIVERED, 'Доставлен'),
    )

    first_name = models.CharField(max_length=64)
    last_name = models.CharField(max_length=64)
    email = models.EmailField(max_length=256)
    address = models.CharField(max_length=256)
    basket_history = models.JSONField(default=dict)
    created = models.DateTimeField(auto_now_add=True)
    status = models.SmallIntegerField(default=CREATED, choices=STATUSES)
    initiator = models.ForeignKey(to=User, on_delete=models.CASCADE)

    def __str__(self):
        return f'Order #{self.id}. {self.first_name} {self.last_name}'

    def update_after_payment(self):
        baskets = Basket.objects.filter(user=self.initiator)
        self.status = self.PAID
        self.basket_history = {
            'purchased_items': [basket.de_json() for basket in baskets],
            'total_sum': float(baskets.total_sum()),
        }
        baskets.delete()
        self.save()


class Resume(models.Model):
    file = models.FileField(upload_to='files/', null=True)
    initiator = models.ForeignKey(to=User, on_delete=models.CASCADE, null=True)

    class Meta:
        verbose_name = 'files'
        verbose_name_plural = 'files'

    def __repr__(self):
        return 'Resume(%s)' % self.file

    # def __str__(self):
    #     return self.file


class Task(models.Model):
    NOT_COMPLETE = 0
    IN_PROGRESS = 1
    DONE = 2

    STATUSES = (
        (NOT_COMPLETE, 'Не завершено'),
        (IN_PROGRESS, 'В процессе'),
        (DONE, 'Готово'),
    )

    name = models.CharField(max_length=40)
    date = models.DateTimeField(auto_now_add=True)
    expired = models.DateTimeField()
    status = models.SmallIntegerField(default=NOT_COMPLETE, choices=STATUSES)
    description = models.CharField(max_length=256)
    initiator = models.ForeignKey(to=User, on_delete=models.CASCADE)
    file = models.ForeignKey(to=Resume, on_delete=models.CASCADE, null=True, blank=True)

    class Meta:
        verbose_name = 'tasks'
        verbose_name_plural = 'tasks'

    def __str__(self):
        return self.name


@property
def is_past_due(self):
    return date.today() == self.date

orders/forms.py
from django import forms

from orders.models import Order, Resume, Task


class OrderForm(forms.ModelForm):
    first_name = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Иван'}))
    last_name = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Иванов'}))
    email = forms.EmailField(widget=forms.EmailInput(
        attrs={'class': 'form-control', 'placeholder': 'you@example.com'}))
    address = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control',
               'placeholder': 'Россия, Москва, ул. Мира, дом 6',
               }))

    class Meta:
        model = Order
        fields = ('first_name', 'last_name', 'email', 'address')


class TaskForm(forms.ModelForm):
    name = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Введите название задачи'}))
    # date = forms.DateTimeField(widget=forms.DateTimeInput(
    #     attrs={'class': 'form-control', 'placeholder': '2'}))
    expired = forms.DateTimeField(widget=forms.DateInput(
        attrs={'class': 'form-control', 'placeholder': '01.01.1900'}))
    status = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    description = forms.CharField(widget=forms.Textarea(
        attrs={'class': 'form-control', 'placeholder': 'Введите описание',
               'rows': 1}))
    initiator = forms.CharField(widget=forms.HiddenInput(), initial=1)

    class Meta:
        model = Task
        fields = ['name', 'expired', 'status', 'description']
        # labels = {
        #     'title': 'Название Модели',
        #     'material': 'Материал',
        #     'priority': 'Приоритет сортировки',
        #     'is_active': 'Активна (включена)',
        # }


class ResumeForm(forms.ModelForm):
    class Meta:
        model = Resume
        fields = ['file']

orders/views.py
from http import HTTPStatus

import stripe
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse, reverse_lazy
from django.views.decorators.csrf import csrf_exempt
from django.views.generic.base import TemplateView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView
from django.views.generic.list import ListView

from common.views import TitleMixin
from orders.forms import OrderForm, TaskForm
from orders.models import Order, Task, Resume
from products.models import Basket
from .forms import ResumeForm

stripe.api_key = settings.STRIPE_SECRET_KEY


class SuccessTemplateView(TitleMixin, TemplateView):
    template_name = 'orders/success.html'
    title = 'Store - Спасибо за заказ!'


class CanceledTemplateView(TemplateView):
    template_name = 'orders/cancled.html'


class OrderListView(TitleMixin, ListView):
    template_name = 'orders/orders.html'
    title = 'Store - Заказы'
    queryset = Order.objects.all()
    ordering = ('-created')

    def get_queryset(self):
        queryset = super(OrderListView, self).get_queryset()
        return queryset.filter(initiator=self.request.user)


class OrderDetailView(DetailView):
    template_name = 'orders/order.html'
    model = Order

    def get_context_data(self, **kwargs):
        context = super(OrderDetailView, self).get_context_data(**kwargs)
        context['title'] = f'Store - Заказ #{self.object.id}'
        return context


class OrderCreateView(TitleMixin, CreateView):
    template_name = 'orders/order-create.html'
    form_class = OrderForm
    success_url = reverse_lazy('orders:order_create')
    title = 'Store - Оформление заказа'

    def post(self, request, *args, **kwargs):
        super(OrderCreateView, self).post(request, *args, **kwargs)
        baskets = Basket.objects.filter(user=self.request.user)
        checkout_session = stripe.checkout.Session.create(
            line_items=baskets.stripe_products(),
            metadata={'order_id': self.object.id},
            mode='payment',
            success_url='{}{}'.format(settings.DOMAIN_NAME,
                                      reverse('orders:order_success')),
            cancel_url='{}{}'.format(settings.DOMAIN_NAME,
                                     reverse('orders:order_canceled')),
        )
        return HttpResponseRedirect(checkout_session.url,
                                    status=HTTPStatus.SEE_OTHER)

    def form_valid(self, form):
        form.instance.initiator = self.request.user
        return super(OrderCreateView, self).form_valid(form)


@csrf_exempt
def stripe_webhook_view(request):
    payload = request.body
    sig_header = request.META['HTTP_STRIPE_SIGNATURE']
    event = None

    try:
        event = stripe.Webhook.construct_event(
            payload, sig_header, settings.STRIPE_WEBHOOK_SECRET
        )
    except ValueError:
        # Invalid payload
        return HttpResponse(status=400)
    except stripe.error.SignatureVerificationError:
        # Invalid signature
        return HttpResponse(status=400)

    # Handle the checkout.session.completed event
    if event['type'] == 'checkout.session.completed':
        session = event['data']['object']

        # Fulfill the purchase...
        fulfill_order(session)

    # Passed signature verification
    return HttpResponse(status=200)


def fulfill_order(session):
    order_id = int(session.metadata.order_id)
    order = Order.objects.get(id=order_id)
    order.update_after_payment()


@login_required
def main(request):
    count = len(Task.objects.filter(initiator=request.user))
    context = {
        'title': 'Kanban - Главная',
        'tasks': Task.objects.filter(initiator=request.user),
        'count': count
    }
    return render(request, 'orders/main.html', context)


@login_required
def mytasks(request):
    context = {
        'title': 'KanbanPM - Задачи',
        'tasks': Task.objects.filter(initiator=request.user)
    }
    return render(request, 'orders/my-tasks.html', context)


@login_required
def board(request):
    if request.method == 'POST':
        form = TaskForm(request.POST)
        if form.is_valid():
            temp = form.save(commit=False)
            temp.initiator = request.user
            temp.save()
            return redirect('orders:board')
        else:
            print("ERROR : Form is invalid")
            print(form.errors)
    else:
        form = TaskForm()
    context = {
        'title': 'Kanban - Доска',
        'tasks': Task.objects.filter(initiator=request.user),
        'form': form
    }
    return render(request, 'orders/board.html', context)


def handle_uploaded_file(f):
    with open('test.txt', 'wb+') as destination:
        for chunk in f.chunks():
            destination.write(chunk)


def upload(request):
    if request.method == 'POST':
        form = ResumeForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect("/")
    else:
        form = ResumeForm
        context = {
            'form': form
        }
    return render(request, 'orders/upload.html', context)


def upload_file(request):
    if request.method == "POST":
        form = ResumeForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect("orders/board/")
    else:
        form = ResumeForm()
    return render(request, "orders/upload.html", {"form": form})


@login_required
def download_file(request, file_id):
    file = get_object_or_404(Resume, pk=file_id)
    response = HttpResponse(file.file, content_type='application/pdf')
    response['Content-Disposition'] = f'attachment; filename="{file.file}"'
    return response


@login_required
def calender(request):
    context = {
        'title': 'Kanban - Календарь',
        'tasks': Task.objects.filter(initiator=request.user)
    }
    return render(request, 'orders/calender.html', context)


# class AddTask(TitleMixin, SuccessMessageMixin, CreateView):
#     model = Task
#     form_class = TaskForm
#     template_name = 'orders/add-task.html'
#     success_url = reverse_lazy('users:login')
#     success_message = 'Задача успешно добавлена!'
#     title = 'KanbanPM - Добавление задачи'

@login_required
def anna(request):
    count = len(Task.objects.filter(initiator=request.user))
    context = {
        'title': 'Kanban - Главная',
        'tasks': Task.objects.filter(initiator=request.user),
        'count': count
    }
    return render(request, 'orders/Anna.html', context)


@login_required
def listing(request):
    context = {
        'title': 'Kanban - Список',
        'tasks': Task.objects.filter(initiator=request.user)
    }
    return render(request, 'orders/list.html', context)

orders/templates/orders/add-task.html
{% extends 'products/base.html' %}
{% load humanize %}
{% load static %}

{% block css %}
<link href="{% static 'vendor/css/main.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}

<script src="{% static 'vendor/js/date.js' %}"></script>
<!-- Основное содержимое страницы -->

<form action="{% url 'users:registration' %}" method="POST">
  {{ form.as_p }}
  <div class="form-group mt-4 mb-0">
    <input class="btn btn-primary btn-block" type="submit" value="Создать аккаунт">
  </div>
</form>

{% endblock %}

orders/templates/orders/calender.html
{% extends 'orders/base.html' %}
{% load humanize %}
{% load static %}

{% block css %}
<link href="{% static 'vendor/css/Anna.css' %}" rel="stylesheet">
<link href="{% static 'vendor/fullcalendar/packages/core/main.css' %}" rel="stylesheet">
<link href="{% static 'vendor/fullcalendar/packages/daygrid/main.css' %}" rel="stylesheet">
<link rel="stylesheet" href="{% static 'vendor/bootstrap/css/bootstrap.min.css">
<link rel="stylesheet" href="{% static 'vendor/fonts/icomoon/style.css' %}">
<link href="https://fonts.googleapis.com/css?family=Roboto:300,400&amp;display=swap" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500&amp;display=swap" rel="stylesheet">
<link rel="stylesheet" href="{% static 'vendor/css/style.css' %}">
{% endblock %}

<script defer="" referrerpolicy="origin"
        src="/cdn-cgi/zaraz/s.js?z=JTdCJTIyZXhlY3V0ZWQlMjIlM0ElNUIlNUQlMkMlMjJ0JTIyJTNBJTIyQ2FsZW5kYXIlMjAlMjM5JTIyJTJDJTIyeCUyMiUzQTAuODYyMzcwNDY4NDM3ODgzMiUyQyUyMnclMjIlM0ExOTIwJTJDJTIyaCUyMiUzQTEwODAlMkMlMjJqJTIyJTNBOTA2JTJDJTIyZSUyMiUzQTE5MjAlMkMlMjJsJTIyJTNBJTIyaHR0cHMlM0ElMkYlMkZwcmV2aWV3LmNvbG9ybGliLmNvbSUyRnRoZW1lJTJGYm9vdHN0cmFwJTJGY2FsZW5kYXItMTklMkYlMjIlMkMlMjJyJTIyJTNBJTIyaHR0cHMlM0ElMkYlMkZhZG1pbmx0ZS5pbyUyRiUyMiUyQyUyMmslMjIlM0EyNCUyQyUyMm4lMjIlM0ElMjJVVEYtOCUyMiUyQyUyMm8lMjIlM0EtMTgwJTJDJTIycSUyMiUzQSU1QiU1RCU3RA=="></script>
<script nonce="d4559d23-3a81-45a9-8705-c5e680139deb">
    (function(w,d){!function(a,b,c,d){a[c]=a[c]||{};a[c].executed=[];a.zaraz={deferred:[],listeners:[]};a.zaraz.q=[];a.zaraz._f=function(e){return function(){var f=Array.prototype.slice.call(arguments);a.zaraz.q.push({m:e,a:f})}};for(const g of["track","set","debug"])a.zaraz[g]=a.zaraz._f(g);a.zaraz.init=()=>{var h=b.getElementsByTagName(d)[0],i=b.createElement(d),j=b.getElementsByTagName("title")[0];j&&(a[c].t=b.getElementsByTagName("title")[0].text);a[c].x=Math.random();a[c].w=a.screen.width;a[c].h=a.screen.height;a[c].j=a.innerHeight;a[c].e=a.innerWidth;a[c].l=a.location.href;a[c].r=b.referrer;a[c].k=a.screen.colorDepth;a[c].n=b.characterSet;a[c].o=(new Date).getTimezoneOffset();if(a.dataLayer)for(const n of Object.entries(Object.entries(dataLayer).reduce(((o,p)=>({...o[1],...p[1]})),{})))zaraz.set(n[0],n[1],{scope:"page"});a[c].q=[];for(;a.zaraz.q.length;){const q=a.zaraz.q.shift();a[c].q.push(q)}i.defer=!0;for(const r of[localStorage,sessionStorage])Object.keys(r||{}).filter((t=>t.startsWith("_zaraz_"))).forEach((s=>{try{a[c]["z_"+s.slice(7)]=JSON.parse(r.getItem(s))}catch{a[c]["z_"+s.slice(7)]=r.getItem(s)}}));i.referrerPolicy="origin";i.src="/cdn-cgi/zaraz/s.js?z="+btoa(encodeURIComponent(JSON.stringify(a[c])));h.parentNode.insertBefore(i,h)};["complete","interactive"].includes(b.readyState)?zaraz.init():a.addEventListener("DOMContentLoaded",zaraz.init)}(w,d,"zarazData","script");})(window,document);
</script>

{% block content %}
<script src="{% static 'vendor/js/date.js' %}"></script>
<main>
    <div class="content">
        <div id="current-week" style="text-align:center;"></div>
    <script>
      var currentWeekElement = document.getElementById('current-week');
      var currentDate = new Date();
      var currentWeek = getWeekNumber(currentDate);

      var startDate = new Date();
      startDate.setDate(currentDate.getDate() - currentDate.getDay() + 1);
      var endDate = new Date(startDate);
      endDate.setDate(startDate.getDate() + 6);

      var startDateString = formatDate(startDate);
      var endDateString = formatDate(endDate);

      currentWeekElement.innerHTML = 'Текущая неделя: ' + startDateString + ' - ' + endDateString;

      function getWeekNumber(date) {
        var newDate = new Date(date);
        newDate.setHours(0, 0, 0, 0);
        newDate.setDate(newDate.getDate() + 4 - (newDate.getDay() || 7));
        var yearStart = new Date(newDate.getFullYear(), 0, 1);
        var weekNumber = Math.ceil(((newDate - yearStart) / 86400000 + 1) / 7);
        return weekNumber;
      }

      function formatDate(date) {
        var day = date.getDate();
        var month = date.getMonth() + 1;
        var year = date.getFullYear();
        return ('0' + day).slice(-2) + '.' + ('0' + month).slice(-2) + '.' + year;
      }
    </script>
 <div id="calendar" class="fc fc-ltr fc-unthemed" style="">

    </div>
</div>
<script src="{% static 'vendor/js/jquery-3.3.1.min.js' %}"></script>
<script src="{% static 'vendor/js/popper.min.js' %}"></script>
<script src="{% static 'vendor/js/bootstrap.min.js' %}"></script>
<script src="{% static 'vendor/fullcalendar/packages/core/main.js' %}"></script>
<script src="{% static 'vendor/fullcalendar/packages/interaction/main.js' %}"></script>
<script src="{% static 'vendor/fullcalendar/packages/daygrid/main.js' %}"></script>
<script>

  document.addEventListener('DOMContentLoaded', function() {
    var calendarEl = document.getElementById('calendar');

    var calendar = new FullCalendar.Calendar(calendarEl, {
      plugins: [ 'interaction', 'dayGrid' ],
      defaultDate: '2023-06-12',
      editable: true,
      eventLimit: true, // allow "more" link when too many events,
      locale: 'ru', // Указываем языковой код русской локализации
      events: [
        {% for task in tasks %}
        {
          title: '{{ task.name }}',
          start: '{{ task.date|date:"Y-m-d" }}',
          end: '{{ task.date|date:"Y-m-d" }}',
          description: '{{ task.description }}',
          status: '{{ task.status }}',
          initiator: '{{ task.initiator }}'
        },
        {% endfor %}
      ]
    });

    calendar.render();
  });

</script>
<script src="{% static 'vendor/js/main.js' %}"></script>
<script defer=""
        src="https://static.cloudflareinsights.com/beacon.min.js/v52afc6f149f6479b8c77fa569edb01181681764108816"
        integrity="sha512-jGCTpDpBAYDGNYR5ztKt4BQPGef1P0giN6ZGVUi835kFF88FOmmn8jBQWNgrNd8g/Yu421NdgWhwQoaOPFflDw=="
        data-cf-beacon="{&quot;rayId&quot;:&quot;7cf92f7d0d582d83&quot;,&quot;token&quot;:&quot;cd0b4b3a733644fc843ef0b185f98241&quot;,&quot;version&quot;:&quot;2023.4.0&quot;,&quot;si&quot;:100}"
        crossorigin="anonymous"></script>

{% endblock %}

orders/templates/orders/cancled.html
<!DOCTYPE html>
<html>
<head>
    <title>Checkout canceled</title>
    <link rel="stylesheet" href="style.css">
</head>
<body>
<section>
    <p>Forgot to add something to your cart? Shop around then come back to pay!</p>
</section>
</body>
</html>

orders/templates/orders/files.html
{% extends 'orders/base.html' %}
{% load humanize %}

{% block content %}
    <section>
        <div class="container pt-5">
            <div class="text-center mt-5">
                <h1>Заказы</h1>
                <div class="orders mt-5">
                    <table class="table">
                        <thead>
                        <tr class="table-light">
                            <th scope="col">#</th>
                            <th scope="col">Статус</th>
                            <th scope="col">Создан</th>
                            <th scope="col">Итого</th>
                            <th scope="col">Действие</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for order in object_list %}
                            <tr>
                                <th scope="row">{{ order.id }}</th>
                                <td>{{ order.get_status_display }}</td>
                                <td>{{ order.created|naturaltime }}</td>
                                <td>{{ order.basket_history.total_sum|intcomma }} руб.</td>
                                <td>
                                    <a href="{% url 'orders:order' order.id %}">просмотреть</a>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

orders/templates/orders/order-create.html
{% extends 'products/base.html' %}
{% load humanize %}

{% block content %}
    <section>
        <div class="alert alert-warning text-center" role="alert">
            Пожалуйста, заполните адрес электронной почты.
        </div>
        <div class="container">
            <div class="py-5 text-center">
                <h1>Оформление заказа</h1>
            </div>
            <div class="row g-5">
                <div class="col-md-5 col-lg-4 order-md-last">
                    <h4 class="d-flex justify-content-between align-items-center mb-3">
                        <span class="text-primary">Корзина</span>
                        <span class="badge badge-primary badge-pill text-white">{{ baskets.total_quantity }}</span>
                    </h4>
                    <ul class="list-group mb-3">
                        {% for basket in baskets %}
                            <li class="list-group-item d-flex justify-content-between lh-sm">
                                <div>
                                    <h6 class="my-0">{{ basket.product.name }}</h6>
                                    <small class="text-muted">{{ basket.quantity }} шт.</small>
                                </div>
                                <span class="text-muted">{{ basket.sum|intcomma }} руб.</span>
                            </li>
                        {% endfor %}
                        <li class="list-group-item d-flex justify-content-between">
                            <span>Сумма к оплате</span>
                            <strong>{{ baskets.total_sum|intcomma }} руб.</strong>
                        </li>
                    </ul>
                </div>
                <div class="col-md-7 col-lg-8">
                    <h4 class="mb-3">Адрес доставки</h4>
                    <form action="{% url 'orders:order_create' %}" method="post">
                        {% csrf_token %}
                        <div class="row g-3">
                            <div class="col-sm-6">
                                <label for="{{ form.first_name.id_for_label }}" class="form-label">Имя</label>
                                {{ form.first_name }}
                            </div>

                            <div class="col-sm-6">
                                <label for="{{ form.last_name.id_for_label }}" class="form-label">Фамилия</label>
                                {{ form.last_name }}
                            </div>

                            <div class="col-12 mt-3">
                                <label for="{{ form.email.id_for_label }}" class="form-label">Адрес электронной
                                    почты</label>
                                {{ form.email }}
                            </div>

                            <div class="col-12 mt-3">
                                <label for="{{ form.email.address }}" class="form-label">Адрес</label>
                                {{ form.address }}
                            </div>

                        </div>

                        <hr class="my-4">

                        <button class="w-100 btn btn-primary btn-lg" type="submit">Продолжить</button>
                    </form>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

orders/templates/orders/orders.html
{% extends 'products/base.html' %}
{% load humanize %}

{% block content %}
    <section>
        <div class="container pt-5">
            <div class="text-center mt-5">
                <h1>Заказы</h1>
                <div class="orders mt-5">
                    <table class="table">
                        <thead>
                        <tr class="table-light">
                            <th scope="col">#</th>
                            <th scope="col">Статус</th>
                            <th scope="col">Создан</th>
                            <th scope="col">Итого</th>
                            <th scope="col">Действие</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for file in files %}
                            <tr>
                                <th scope="row">{{ file.id }}</th>
                                <td>{{ file.initiator }}</td>
<!--                                <td>{{ order.created|naturaltime }}</td>-->
<!--                                <td>{{ order.basket_history.total_sum|intcomma }} руб.</td>-->
                                <td>
                                    <a href="{% url 'orders:files' file.id %}">просмотреть</a>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </section>
{% endblock %}