store/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from orders.views import stripe_webhook_view
from products.views import IndexView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),
    path('products/', include('products.urls', namespace='products')),
    path('users/', include('users.urls', namespace='users')),
    path('accounts/', include('allauth.urls')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('webhook/stripe/', stripe_webhook_view, name='stripe_webhook'),

    path('', include('django.contrib.auth.urls')),
]


if settings.DEBUG:
    urlpatterns.append(path('__debug__/', include('debug_toolbar.urls')))
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
import django
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LogoutView, PasswordResetConfirmView
from django.urls import path

from users.views import (EmailVerificationView, UserLoginView, UserProfileView,
                         UserRegistrationView, PassResetView, PassDoneView,
                         PassConfirmView, reset_password_message)

app_name = 'users'

urlpatterns = [
    path('login/', UserLoginView.as_view(), name='login'),
    path('registration/', UserRegistrationView.as_view(), name='registration'),
    path('profile/<int:pk>/', login_required(UserProfileView.as_view()), name='profile'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('verify/<str:email>/<uuid:code>/', EmailVerificationView.as_view(), name='email_verification'),

    url(r'^password-reset/$', reset_password_message, name='password_reset'),
    url(r'^password-reset/done/$', PassDoneView.as_view(), name='password_reset_done'),
    # url(r'^password-reset/confirm/(?P<uidb64>[-\w]+)/(?P<token>[-\w]+)/$', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    url(r'^password-reset/complete/$', django.contrib.auth.views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

users/models.py
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.core.mail import send_mail
from django.db import models
from django.urls import reverse
from django.utils.timezone import now


class User(AbstractUser):
    image = models.ImageField(upload_to='users_images', null=True, blank=True)
    is_verified_email = models.BooleanField(default=False)


class EmailVerification(models.Model):
    code = models.UUIDField(unique=True, null=True)
    user = models.ForeignKey(to=User, null=True, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True, null=True)
    expiration = models.DateTimeField()

    def __str__(self):
        return f'EmailVerification object for {self.user.email}'

    def send_verification_email(self):
        link = reverse('users:email_verification', kwargs={'email': self.user.email, 'code': self.code})
        verification_link = f'{settings.DOMAIN_NAME}{link}'
        subject = f'Подтверждение учетной записи для {self.user.username}'
        message = 'Для подтверждения учетной записи для {} перейдите по ссылке: {}'.format(
            self.user.email,
            verification_link
        )
        send_mail(
            subject=subject,
            message=message,
            from_email=settings.EMAIL_HOST_USER,
            recipient_list=[self.user.email],
            fail_silently=False,
        )

    def is_expired(self):
        return True if now() >= self.expiration else False

users/forms.py
from django import forms
from django.contrib.auth.forms import (AuthenticationForm, UserChangeForm,
                                       UserCreationForm)

from users.models import User
from users.tasks import send_email_verification


class UserLoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control py-4', 'placeholder': 'Введите адрес эл. почты '}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control py-4', 'placeholder': 'Введите пароль'}))

    class Meta:
        model = User
        fields = ('username', 'password')


class UserRegistrationForm(UserCreationForm):
    first_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control py-4', 'placeholder': 'Введите имя'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control py-4', 'placeholder': 'Введите фамилию'}))
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control py-4', 'placeholder': 'Введите имя пользователя'}))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'class': 'form-control py-4', 'placeholder': 'Введите адрес эл. почты'}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control py-4', 'placeholder': 'Введите пароль'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control py-4', 'placeholder': 'Подтвердите пароль'}))

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email', 'password1', 'password2')

    def save(self, commit=True):
        user = super(UserRegistrationForm, self).save(commit=True)
        send_email_verification.delay(user.id)
        return user


class UserProfileForm(UserChangeForm):
    first_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control py-4'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control py-4'}))
    image = forms.ImageField(widget=forms.FileInput(attrs={'class': 'custom-file-input'}), required=False)
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control py-4', 'readonly': True}))
    email = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control py-4', 'readonly': True}))

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'image', 'username', 'email')

users/views.py
from django.contrib import messages
from django.contrib.auth.views import LoginView, PasswordResetDoneView, PasswordResetView, PasswordResetConfirmView
from django.contrib.auth.forms import PasswordResetForm
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import HttpResponseRedirect, render, redirect
from django.urls import reverse, reverse_lazy
from django.views.generic.base import TemplateView
from django.views.generic.edit import CreateView, UpdateView
from django.template.loader import render_to_string
from django.contrib.sites.shortcuts import get_current_site
from django.utils.http import urlsafe_base64_encode
from django.utils.encoding import force_bytes, force_str
from django.db.models.query_utils import Q
from django.contrib.auth.tokens import default_token_generator
from django.core.mail import EmailMessage, send_mail
from django.http import HttpResponse

from common.views import TitleMixin
from users.forms import UserLoginForm, UserProfileForm, UserRegistrationForm
from users.models import EmailVerification, User
from .tokens import account_activation_token


class UserLoginView(TitleMixin, LoginView):
    template_name = 'users/login.html'
    form_class = UserLoginForm
    title = 'KanbanPM - Авторизация'


class UserRegistrationView(TitleMixin, SuccessMessageMixin, CreateView):
    model = User
    form_class = UserRegistrationForm
    template_name = 'users/registration.html'
    success_url = reverse_lazy('users:login')
    success_message = 'Вы успешно зарегестрированы!'
    title = 'KanbanPM - Регистрация'


class UserProfileView(TitleMixin, UpdateView):
    model = User
    form_class = UserProfileForm
    template_name = 'users/profile.html'
    title = 'KanbanPM - Личный кабинет'

    def get_success_url(self):
        return reverse_lazy('users:profile', args=(self.object.id,))


class EmailVerificationView(TitleMixin, TemplateView):
    title = 'KanbanPM - подтвеждение электронной почты'
    template_name = 'users/email_verification.html'

    def get(self, request, *args, **kwargs):
        code = kwargs['code']
        user = User.objects.get(email=kwargs['email'])
        email_verifications = EmailVerification.objects.filter(user=user, code=code)
        if email_verifications.exists() and not email_verifications.first().is_expired():
            user.is_verified_email = True
            user.save()
            return super(EmailVerificationView, self).get(request, *args, **kwargs)
        else:
            return HttpResponseRedirect(reverse('index'))


class PassResetView(PasswordResetView):
    title = 'KanbanPM - Восстановление пароля'
    template_name = "users/password_reset_form.html"
    success_url = reverse_lazy('users:password_reset_done')


class PassDoneView(PasswordResetDoneView):
    title = 'KanbanPM - Восстановление пароля'
    template_name = 'users/password_reset_done.html'


class PassConfirmView(PasswordResetConfirmView):
    title = 'KanbanPM - Изменение пароля'
    template_name = 'users/password_reset_confirm.html'
    success_url = reverse_lazy('users:password_reset_complete')


def reset_password_message(request):
    if request.method == "POST":
        password_form = PasswordResetForm(request.POST)
        if password_form.is_valid():
            data = password_form.cleaned_data['email']
            user_email = User.objects.filter(Q(email=data))
            if user_email.exists():
                for user in user_email:
                    subject = 'Password Request'
                    email_template_name = 'users/password_message.txt'
                    parameters = {
                        'email': user.email,
                        'username': user.username,
                        'domain': '127.0.0.1:8000',
                        'temp': '/users/password-reset/confirm',
                        'site_name': 'KanbanPM',
                        'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                        'token': default_token_generator.make_token(user),
                        'protocol': 'http'
                    }
                    email = render_to_string(email_template_name, parameters)
                    try:
                        send_mail(subject, email, '', [user.email], fail_silently=False)
                    except:
                        return HttpResponse('Invalid Header')
                    return redirect('users:password_reset_done')
    else:
        password_form = PasswordResetForm()
    context = {
        'form': password_form
    }
    return render(request, 'users/password_reset_form.html', context)

users/templates/users/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en" >
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <title>{{ title }}</title>

    <link href="{% static 'vendor/css/auth.css' %}" rel="stylesheet"/>
    <link href="{% static 'vendor/img/favicon.ico' %}" rel="icon">
{% block additional_css %}{% endblock %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/js/all.min.js"
            crossorigin="anonymous"></script>
</head>
<body class="bg-primary">
<div id="layoutAuthentication">
    <div id="layoutAuthentication_content">
        {% block content %} {% endblock %}
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
        crossorigin="anonymous"></script>
<script src="{% static 'vendor/js/auth.js' %}"></script>
</body>
</html>

users/templates/users/email_verification.html
{% extends 'users/base.html' %}

{% block content %}
    <main>
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-5">
                    <div class="card shadow-lg border-0 rounded-lg mt-5">
                        <div class="card-header"><h3 class="text-center font-weight-light my-4">Поздравляем</h3>
                        </div>
                        <div class="card-body text-center">
                            <h4>Ваша учетная запись успешно подтверждена!</h4>
                        </div>
                        <div class="card-footer text-center">
                            <div class="small"><a href="{% url 'users:login' %}">Продолжить</a></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock %}

users/templates/users/login.html
{% extends 'users/base.html' %}

{% load static %}
{% block additional_css %}
    <link href="{% static 'vendor/css/login.css' %}" rel="stylesheet"/>
{% endblock %}

{% block content %}
<main>
    <div class="container-fluid" style="padding-left: 0;">

        <div class="row align-items-center">
             <div class="col-7 bg1"></div>


            <div class="col-4 mx-auto text-center" style="position: relative;">
                {% if messages or form.non_field_errors %}
                    <div class="alert
                    {% if messages %} alert-success {% else %} alert-warning {% endif %}
                     alert-dismissible fade show" role="alert"
                         style="margin-top: 50px;">
                        {% if messages %}
                            {% for message in messages %}
                                {{ message }}
                            {% endfor %}
                        {% else %}
                            {{ form.non_field_errors }}
                        {% endif %}
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                {% endif %}
                <div class="card shadow-lg border-0 rounded-lg mt-5">
                    <div class="card-header border-left border-right border-top custom-rounded ">
                        <h1 class="text-center font-weight-light my-3">Войти в KanbanPM</h1>
                    </div>
                    <div class="card-body border-left border-right border-top">
                        <form action="{% url 'users:login' %}" method="post">
                            {% csrf_token %}
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.username.id_for_label }}">
                                    Адрес электронной почты
                                </label>
                                {{ form.username }}
                            </div>
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.password.id_for_label }}">
                                    Пароль
                                </label>
                                {{ form.password }}
                            </div>
                            <div class="form-group d-flex align-items-center justify-content-between mt-4 mb-0">
                                <a class="small" href="{% url 'users:password_reset' %}">Забыли пароль?</a>
                                <input class="btn btn-primary" type="submit" value="Авторизоваться">
                            </div>

                        </form>
                    </div>
                    <div class="card-footer text-center border-left border-right border-top ">
                        <div class="small">Нужен аккаунт?<a href="{% url 'users:registration' %}">
                            <u>Зарегистрируйся!</u></a></div>
                    </div>
                </div>
            </div>
        </div>

    </div>
</main>
{% endblock %}

users/templates/users/password_resert_email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
  <h1>Someone asked for password reset for email {{ email }}. Follow thelink below:
    {{ protocol }}://{{ domain }}{% url "users:password_reset_confirm" uidb64=uid token=token %}
    Your username, in case you've forgotten: {{ user.get_username }}</h1>
</body>
</html>

users/templates/users/password_reset_complete.html
{% extends 'users/base.html' %}
{% load static %}

{% block title %}
<title>{{ title }}</title>
{% endblock %}

{% block additional_css %}
    <link href="{% static 'vendor/css/login.css' %}" rel="stylesheet"/>
{% endblock %}

{% block content %}
<main>
    <div class="container-fluid" style="padding-left: 0;">

        <div class="row align-items-center">
             <div class="col-7 bg1"></div>


            <div class="col-4 mx-auto text-center" style="position: relative;">
                <div class="card shadow-lg border-0 rounded-lg mt-5">
                    <div class="card-header border-left border-right border-top custom-rounded ">
                        <h1 class="text-center font-weight-light my-3">Восстановление пароля</h1>
                    </div>
                    <div class="card-body border-left border-right border-top">
                        <p style="font-size: 19px">Ваш пароль успешно изменен!</p>
                    </div>
                </div>
            </div>
        </div>

    </div>
</main>
{% endblock %}

users/templates/users/password_reset_confirm.html
{% extends 'users/base.html' %}
{% load static %}

{% block title %}
<title>{{ title }}</title>
{% endblock %}

{% block additional_css %}
<link href="{% static 'vendor/css/login.css' %}" rel="stylesheet"/>
{% endblock %}

{% block content %}
<main>
    {% if validlink %}
        <div class="container-fluid" style="padding-left: 0;">

            <div class="row align-items-center">
                <div class="col-7 bg1"></div>


                <div class="col-4 mx-auto text-center" style="position: relative;">
                    {% if messages or form.non_field_errors %}
                    <div class="alert
                        {% if messages %} alert-success {% else %} alert-warning {% endif %}
                         alert-dismissible fade show" role="alert"
                         style="margin-top: 50px;">
                        {% if messages %}
                            {% for message in messages %}
                                {{ message }}
                            {% endfor %}
                            {% else %}
                                {{ form.non_field_errors }}
                        {% endif %}
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    {% endif %}
                    <div class="card shadow-lg border-0 rounded-lg mt-5">
                        <div class="card-header border-left border-right border-top custom-rounded ">
                            <h1 class="text-center font-weight-light my-3">Восстановление пароля</h1>
                        </div>
                        <div class="card-body border-left border-right border-top custom-rounded" style="border-radius: 0 0 calc(0.65rem - 1px) calc(0.65rem - 1px);">
                            <form action="{% url 'users:password_reset_confirm' %}" method="post">
                                {% csrf_token %}
                                <div class="form-group">
                                    {{ form.as_p }}
                                    <input class="btn btn-primary" type="submit" value="Изменить пароль">
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    {% endif %}
</main>
{% endblock %}

users/templates/users/password_reset_done.html
{% extends 'users/base.html' %}
{% load static %}

{% block title %}
<title>{{ title }}</title>
{% endblock %}

{% block additional_css %}
    <link href="{% static 'vendor/css/login.css' %}" rel="stylesheet"/>
{% endblock %}

{% block content %}

<main>
    <div class="container-fluid" style="padding-left: 0;">

        <div class="row align-items-center">
             <div class="col-7 bg1"></div>


            <div class="col-4 mx-auto text-center" style="position: relative;">
                <div class="card shadow-lg border-0 rounded-lg mt-5">
                    <div class="card-header border-left border-right border-top custom-rounded ">
                        <h1 class="text-center font-weight-light my-3">Восстановление пароля</h1>
                    </div>
                    <div class="card-body border-left border-right border-top">
                        <p style="font-size: 19px">Мы отправили вам инструкцию по установке нового пароля на указанный адрес электронной почты (если в нашей базе данных есть такой адрес). Вы должны получить ее в ближайшее время.
Если вы не получили письмо, пожалуйста, убедитесь, что вы ввели адрес с которым Вы зарегистрировались, и проверьте папку со спамом.</p>
                    </div>
                </div>
            </div>
        </div>

    </div>
</main>
{% endblock %}

users/templates/users/password_reset_form.html
{% extends 'users/base.html' %}
{% load static %}

{% block title %}
<title>{{ title }}</title>
{% endblock %}

{% block additional_css %}
<link href="{% static 'vendor/css/login.css' %}" rel="stylesheet"/>
{% endblock %}

{% block content %}
<main>
    <div class="container-fluid" style="padding-left: 0;">

        <div class="row align-items-center">
            <div class="col-7 bg1"></div>


            <div class="col-4 mx-auto text-center" style="position: relative;">
                {% if messages or form.non_field_errors %}
                <div class="alert
                    {% if messages %} alert-success {% else %} alert-warning {% endif %}
                     alert-dismissible fade show" role="alert"
                     style="margin-top: 50px;">
                    {% if messages %}
                        {% for message in messages %}
                            {{ message }}
                        {% endfor %}
                        {% else %}
                            {{ form.non_field_errors }}
                    {% endif %}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                {% endif %}
                <div class="card shadow-lg border-0 rounded-lg mt-5">
                    <div class="card-header border-left border-right border-top custom-rounded ">
                        <h1 class="text-center font-weight-light my-3">Восстановление пароля</h1>
                    </div>
                    <div class="card-body border-left border-right border-top custom-rounded" style="border-radius: 0 0 calc(0.65rem - 1px) calc(0.65rem - 1px);">
                        <form action="{% url 'users:password_reset' %}" method="post">
                            {% csrf_token %}
                            <p style="font-size: 14px">Забыли пароль или потеряли доступ к профилю? Введите привязанную
                                к профилю эл. почту, мы отправим вам письмо со ссылкой для восстановления.</p>
                            <div class="form-group">
                                {{ form.as_p }}
                                <input class="btn btn-primary" type="submit" value="Отправить письмо">
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>

    </div>
</main>
{% endblock %}

users/templates/users/registration.html
{% extends 'users/base.html' %}
{% load static %}
{% block additional_css %}
    <link href="{% static 'vendor/css/registration.css' %}" rel="stylesheet"/>
{% endblock %}
{% block content %}
    <main>
        <div class="container-fluid" style="padding-right: 0.76rem;">
            <div class="row align-items-center">

                <div class="col-lg-6" style=" padding-left: 0rem;">
                    {% if form.errors %}
                        <div class="alert alert-warning alert-dismissible fade show" role="alert"
                             style="margin-top: 50px;">
                            {{ form.errors }}
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                    {% endif %}
                    <div class="card shadow-lg border-0 rounded-lg mt-5 ">
                        <div class="card-header border-top border-left"><h1 class="text-center font-weight-light my-4">Создать аккаунт</h1>
                        </div>
                        <div class="card-body border-left">
                            <form action="{% url 'users:registration' %}" method="post">
                                {% csrf_token %}
                                <div class="form-row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label class="small mb-1" for="{{ form.first_name.id_for_label }}">
                                                Имя
                                            </label>
                                            {{ form.first_name }}
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label class="small mb-1" for="{{ form.last_name.id_for_label }}">
                                                Фамилия
                                            </label>
                                            {{ form.last_name }}
                                        </div>
                                    </div>
                                </div>
                                <div class="form-row">
                                    <div class="col-md-6">
                                        <label class="small mb-1" for="{{ form.username.id_for_label }}">
                                            Имя пользователя
                                        </label>
                                        {{ form.username }}
                                    </div>
                                    <div class="col-md-6">
                                        <label class="small mb-1" for="{{ form.email.id_for_label }}">
                                            Адрес электронной почты
                                        </label>
                                        {{ form.email }}
                                    </div>
                                </div>
                                <div class="form-row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label class="small mb-1" for="{{ form.password1.id_for_label }}">
                                                Пароль
                                            </label>
                                            {{ form.password1 }}
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label class="small mb-1" for="{{ form.password2.id_for_label }}">
                                                Подтверждение пароля
                                            </label>
                                            {{ form.password2 }}
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group mt-4 mb-0">
                                    <input class="btn btn-primary btn-block" type="submit" value="Создать аккаунт">
                                </div>
                            </form>
                        </div>
                        <div class="card-footer text-center border-left">
                            <div class="small">
                               Уже есть аккаунт? <a href="{% url 'users:login' %}">
                                     <u>Авторизоваться!</u>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-6 bg1 "></div>
            </div>

        </div>
    </main>
{% endblock %}