orders/urls.py
from django.urls import path

from orders.views import (CanceledTemplateView, OrderCreateView,
                          OrderDetailView, OrderListView, SuccessTemplateView, main, mytasks, board, calender, anna,
                          listing, download_file)

app_name = 'orders'

urlpatterns = [
    path('order-create/', OrderCreateView.as_view(), name='order_create'),
    path('', OrderListView.as_view(), name='orders_list'),
    path('order/<int:pk>/', OrderDetailView.as_view(), name='order'),
    path('order-success/',
         SuccessTemplateView.as_view(),
         name='order_success'),
    path('order-canceled/',
         CanceledTemplateView.as_view(),
         name='order_canceled'),

    path('main/', main, name="main"),
    path('my-tasks/', mytasks, name="my-tasks"),
    path('board/', board, name="board"),
    path('upload/', download_file, name="upload"),
    path('calender', calender, name="calender"),
    path('list/', listing, name="list"),
    # path('add-task/', AddTask.as_view(), name='add-task')

    path('anna/', anna, name="anna")

]

products/urls.py
from django.urls import path

from products.views import ProductsListView, basket_add, basket_remove, SupportListView, support_function

app_name = 'products'

# urlpatterns = [
#     path('', ProductsListView.as_view(), name='index'),
#     path('category/<int:category_id>/', ProductsListView.as_view(), name='category'),
#     path('page/<int:page>/', ProductsListView.as_view(), name='paginator'),
#
#     path('baskets/add/<int:product_id>/', basket_add, name='basket_add'),
#     path('baskets/remove/<int:basket_id>/', basket_remove, name='basket_remove'),
#
#     path('support', SupportListView.as_view(), name='support'),
# ]

urlpatterns = [
    path('', ProductsListView.as_view(), name='index'),
    path('support/', support_function, name='support'),
    path('category/<int:category_id>/', ProductsListView.as_view(), name='category'),
    path('page/<int:page>/', ProductsListView.as_view(), name='paginator'),
    path('baskets/add/<int:product_id>/', basket_add, name='basket_add'),
    path('baskets/remove/<int:basket_id>/', basket_remove, name='basket_remove'),
]

store/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from orders.views import stripe_webhook_view
from products.views import IndexView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),
    path('products/', include('products.urls', namespace='products')),
    path('users/', include('users.urls', namespace='users')),
    path('accounts/', include('allauth.urls')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('webhook/stripe/', stripe_webhook_view, name='stripe_webhook'),

    path('', include('django.contrib.auth.urls')),
]


if settings.DEBUG:
    urlpatterns.append(path('__debug__/', include('debug_toolbar.urls')))
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
import django
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LogoutView, PasswordResetConfirmView
from django.urls import path

from users.views import (EmailVerificationView, UserLoginView, UserProfileView,
                         UserRegistrationView, PassResetView, PassDoneView,
                         PassConfirmView, reset_password_message)

app_name = 'users'

urlpatterns = [
    path('login/', UserLoginView.as_view(), name='login'),
    path('registration/', UserRegistrationView.as_view(), name='registration'),
    path('profile/<int:pk>/', login_required(UserProfileView.as_view()), name='profile'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('verify/<str:email>/<uuid:code>/', EmailVerificationView.as_view(), name='email_verification'),

    url(r'^password-reset/$', reset_password_message, name='password_reset'),
    url(r'^password-reset/done/$', PassDoneView.as_view(), name='password_reset_done'),
    # url(r'^password-reset/confirm/(?P<uidb64>[-\w]+)/(?P<token>[-\w]+)/$', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    url(r'^password-reset/complete/$', django.contrib.auth.views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

products/models.py
import stripe
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.db import models

from users.models import User

stripe.api_key = settings.STRIPE_SECRET_KEY
countries = (("RU", "Россия"), ("US", "США"))


class ProductCategory(models.Model):
    name = models.CharField(max_length=128, unique=True)
    description = models.TextField(null=True, blank=True)

    class Meta:
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=256)
    description = models.TextField()
    price = models.DecimalField(max_digits=8, decimal_places=2)
    quantity = models.PositiveIntegerField(default=0)
    image = models.ImageField(upload_to='products_images')
    stripe_product_price_id = models.CharField(max_length=128,
                                               null=True,
                                               blank=True)
    category = models.ForeignKey(to=ProductCategory, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'product'
        verbose_name_plural = 'products'

    def __str__(self):
        return f'Продукт: {self.name} | ' \
               f'Категория: {self.category.name}'

    def save(self, force_insert=False,
             force_update=False,
             using=None,
             update_fields=None):
        if not self.stripe_product_price_id:
            stripe_product_price = self.create_stripe_product_price()
            self.stripe_product_price_id = stripe_product_price['id']
        super(Product, self).save(force_insert=False, force_update=False, using=None, update_fields=None)

    def create_stripe_product_price(self):
        stripe_product = stripe.Product.create(name=self.name)
        stripe_product_price = stripe.Price.create(
            product=stripe_product['id'], unit_amount=round(self.price * 100), currency='rub')
        return stripe_product_price


class BasketQuerySet(models.QuerySet):
    def total_sum(self):
        return sum(basket.sum() for basket in self)

    def total_quantity(self):
        return sum(basket.quantity for basket in self)

    def stripe_products(self):
        line_items = []
        for basket in self:
            item = {
                'price': basket.product.stripe_product_price_id,
                'quantity': basket.quantity,
            }
            line_items.append(item)
        return line_items


class Basket(models.Model):
    user = models.ForeignKey(to=User, on_delete=models.CASCADE)
    product = models.ForeignKey(to=Product, on_delete=models.CASCADE)
    quantity = models.PositiveSmallIntegerField(default=0)
    created_timestamp = models.DateTimeField(auto_now_add=True)

    objects = BasketQuerySet.as_manager()

    def __str__(self):
        return f'Корзина для {self.user.username} | Продукт: {self.product.name}'

    def sum(self):
        return self.product.price * self.quantity

    def de_json(self):
        basket_item = {
            'product_name': self.product.name,
            'quantity': self.quantity,
            'price': float(self.product.price),
            'sum': float(self.sum()),
        }
        return basket_item


class Support(models.Model):
    first_name = models.CharField(max_length=256)
    last_name = models.CharField(max_length=256)
    # country = models.CharField(max_length=256)
    email = models.EmailField(blank=True)
    number = models.CharField(max_length=11, blank=False)
    discussion = models.TextField()
    happy = models.BooleanField(default=False)

    class Meta:
        verbose_name = 'support'
        verbose_name_plural = 'support'

    def __str__(self):
        return self.first_name

products/forms.py
from django import forms
from django.contrib.auth.forms import (AuthenticationForm, UserChangeForm,
                                       UserCreationForm)
from django.db import models

from products.models import Support

temp = (('RU', "Россия"), ("US", "США"))


class Supporting(forms.ModelForm):
    first_name = forms.CharField(label="Имя", widget=forms.TextInput(attrs={
        'class': 'form-control py-4', 'placeholder': 'Введите имя'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control py-4', 'placeholder': 'Введите фамилию'}))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'class': 'form-control py-4', 'placeholder': 'Введите адрес эл. почты'}))
    number = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control py-4', 'placeholder': 'Введите номер телефона'}))
    discussion = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control py-4', 'placeholder': 'Введите свой вопрос'}))

    # country = forms.CharField(verbose_name='Страна', max_length=5, choices=temp)

    # passwords1 = forms.CharField(widget=forms.TextInput(attrs={
    #     'class': 'form-control py-4', 'placeholder': 'Выберите страну'}))

    class Meta:
        model = Support
        fields = ('first_name', 'last_name', 'email', 'number', 'discussion')

    def __init__(self, *args, **kwargs):
        super(Supporting, self).__init__(*args, **kwargs)
        self.fields['number'].required = False

products/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import HttpResponseRedirect, render, redirect
from django.urls import reverse_lazy
from django.views.generic.base import TemplateView
from django.views.generic.list import ListView

from common.views import TitleMixin
from products.models import Basket, Product, Support, ProductCategory
from products.forms import Supporting
from django.forms import ValidationError


class IndexView(TitleMixin, TemplateView):
    template_name = 'products/index.html'
    title = 'KanbanPM'


class ProductsListView(TitleMixin, ListView):
    model = Product
    template_name = 'products/products.html'
    paginate_by = 3
    title = 'KanbanPM'

    def get_queryset(self):
        queryset = super(ProductsListView, self).get_queryset()
        category_id = self.kwargs.get('category_id')
        return queryset.filter(category_id=category_id) if category_id else queryset

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ProductsListView, self).get_context_data()
        context['categories'] = ProductCategory.objects.all()
        return context


class SupportListView(TemplateView):
    model = Support
    form_class = Supporting
    template_name = 'products/products.html'
    title = 'KanbanPM - Техническая поддержка'

    # def get_queryset(self):
    #     queryset = super(SupportListView, self).get_queryset()
    #     category_id = self.kwargs.get('category_id')
    #     return queryset.filter(category_id=category_id) if category_id else queryset

    # def get_context_data(self, *, object_list=None, **kwargs):
    #     context = super(SupportListView, self).get_context_data()
    #     context['categories'] = ProductCategory.objects.all()
    #     return context


def support_function(request):
    if request.method == "POST":
        form = Supporting(request.POST)
        if form.is_valid():
            if 'happy' not in request.POST:
                form.add_error(None, 'Подтвердите согласие')
            else:
                form.save()
                return redirect('index')
    else:
        form = Supporting()
    context = {
        'title': 'Техническая поддержка',
        'form': form
    }
    return render(request, 'products/products.html', context)



@login_required
def basket_add(request, product_id):
    product = Product.objects.get(id=product_id)
    baskets = Basket.objects.filter(user=request.user, product=product)

    if not baskets.exists():
        Basket.objects.create(user=request.user, product=product, quantity=1)
    else:
        basket = baskets.first()
        basket.quantity += 1
        basket.save()

    return HttpResponseRedirect(request.META['HTTP_REFERER'])


@login_required
def basket_remove(request, basket_id):
    basket = Basket.objects.get(id=basket_id)
    basket.delete()
    return HttpResponseRedirect(request.META['HTTP_REFERER'])

products/templates/products/base.html
{% load static %}


<!DOCTYPE html>
<html lang="en" style="height: 100vh;">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta meta name="viewport" content="width=device-width, user-scalable=no" />
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{{ title }}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/img/favicon.ico' %}" rel="icon">

    <!-- Custom styles for this template -->
    {% block css %} {% endblock %}

</head>


<body>

<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
        <a class="navbar-brand" href="{% url 'index' %}">KanbanPM</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'products:support' %}"> Техническая поддержка <i class="fas fa-shopping-bag"></i>
                    </a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                           data-bs-toggle="dropdown" aria-expanded="false">
                           <i class="fas fa-user-circle"></i>
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown" >
                            <li>
                                <a class="dropdown-item" href="{% url 'users:profile' user.id %}">Профиль</a>
                            </li>
                            <li><a class="dropdown-item" href="{% url 'orders:main' %}">Главная страница</a></li>
                            {% if user.is_superuser or user.is_staff %}
                                <li>
                                    <a class="dropdown-item" href="{% url 'admin:index' %}">
                                        Панель администратора
                                    </a>
                                </li>
                            {% endif %}
                            <li>
                                <hr class="dropdown-divider">
                            </li>
                            <li>
                                <a class="dropdown-item" href="{% url 'users:logout' %}">
                                    Выйти
                                </a>
                            </li>
                        </ul>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:login' %}">Войти <i class="fas fa-sign-in-alt"></i></a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

{% block content %} {% endblock %}

{% block footer %} {% endblock %}

<!-- Bootstrap core JavaScript -->
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>
<script src="{% static 'vendor/js/script.js' %}"></script>
<script src="{% static 'vendor/js/tasks.js' %}"></script>

<!-- FontAwesome script -->
<script src="{% static 'vendor/fontawesome/fontawesome-icons.js' %}" crossorigin="anonymous"></script>

</body>

</html>

products/templates/products/baskets.html
{% load humanize %}

{% if baskets %}
    <h4 class="mt-3 mb-3 d-flex justify-content-between align-items-center mb-3">
        Корзина <span class="badge badge-secondary badge-pill">{{ baskets.total_quantity }}</span>
    </h4>
    {% for basket in baskets %}
        <div class="card mb-3">
            <div class="card-body">
                <h5 class="card-title">{{ basket.product.name }}</h5>
                <p class="card-text">{{ basket.product.description }}</p>
            </div>
            <ul class="list-group list-group-flush">
                <li class="list-group-item bg-light">
                    <div class="row text-center">
                        <div class="col-lg-4">
                            <input name="basketID" type="number" class="form-control"
                                   value="{{ basket.quantity }}" min="0">
                        </div>
                        <div class="col-lg-4">{{ basket.sum|intcomma }} руб.</div>
                        <div class="col-lg-4">
                            <a href="{% url 'products:basket_remove' basket.id %}">
                                <i class="fas fa-trash"></i>
                            </a>
                        </div>
                    </div>
                </li>
            </ul>
        </div>
    {% endfor %}
    <div class="card mb-3">
        <div class="card-footer">
            <p class="float-left">Итого</p>
            <h4 class="float-right">{{ baskets.total_sum|intcomma }} руб.</h4>
        </div>
    </div>
    <a class="btn btn-success btn-lg float-right" href="{% url 'orders:order_create' %}">
        Оформить заказ
    </a>
{% else %}
    <h4 class="mt-3 mb-3 text-center">
        Корзина пуста
    </h4>
{% endif %}

products/templates/products/index.html
{% extends 'products/base.html' %}
{% load static %}

{% block css %}
    <link href="{% static 'vendor/css/index.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}

    <section>
        <!--    <div class="alert alert-light text-center" role="alert">-->
        <!--        Информационное сообщение-->

        <div class="container">

              <div class="row align-items-center">

                <div class="col-lg-6">
                    <img class="image1" src="{% static 'vendor/img/background2.jpg'%}">
                    <img class="image" src="{% static 'vendor/img/background1.png'%}">

                    <h1 class="mt-5">KanbanPM</h1>
                    <p style = "font-size:18px; ">
                        Визуализируйте рабочие процессы с помощью KanbanPM!
                        <br>Полезная информацию, которую можно извлечь из такой визуализации:
                        <ul class="push">
                        <li>Внимание к незавершенным задачам</li>
                        <li>Гибкость планирования рабочих процессов</li>
                        <li>Контроль сроков выполнения</li>
                        <li>Фокус на задачах, наиболее приоритетных в данный момент</li>
                        <li>Группировка задач по разным статусам</li>
                        </ul>
                    </p>
                    <button id="start-purchase-btn" type="button" class="btn btn-lg">
                        <a id="start-purchase-link" href="{% url 'users:login' %}">
                            Начать работу
                        </a>
                    </button>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

products/templates/products/products.html
{% extends 'products/base.html' %}
{% load static cache humanize %}

{% block css %}
<link href="{% static 'vendor/css/products.css' %}" rel="stylesheet">
{% endblock %}

{% block title %}
<title>{{ title }}</title>
{% endblock %}

{% block content %}
<style>
    .error {
    border: 2px solid red;
}
</style>
<main>

    <div class="container">
        <div class="fon1"></div>
        <div class="row justify-content-center">
            <div class="col-7 mx-auto">

                <div class="card shadow-lg border-0 rounded-lg mt-5">

                    <div class="card-body">
                        <form action="{% url 'products:support' %}" method="post" >
                            {% csrf_token %}
                            <div class="form-row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label class="small mb-1" style="font-size: 110%;"
                                               for="{{ form.first_name.id_for_label }}">
                                            Имя<span class="orange-star">*</span>
                                        </label>
                                        {{ form.first_name }}
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label class="small mb-1" style="font-size: 110%;"
                                               for="{{ form.last_name.id_for_label }}">
                                            Фамилия<span class="orange-star">*</span>
                                        </label>
                                        {{ form.last_name }}
                                    </div>
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="col-md-6">
                                    <label class="small mb-1" style="font-size: 110%;"
                                           for="{{ form.email.id_for_label }}">
                                        Адрес электронной почты<span class="orange-star">*</span>
                                    </label>
                                    {{ form.email }}
                                </div>
                                <div class="col-md-6">
                                    <label class="small mb-1" style="font-size: 110%;"
                                           for="{{ form.number.id_for_label }}">
                                        Телефон<span class="orange-star"></span>
                                    </label>
                                    {{ form.number }}
                                </div>
                            </div>


                            <div class="form-group">
                                <label class="small mb-1 " style="font-size: 110%;"
                                       for="{{ form.discussion.id_for_label }}">
                                    Задайте ваш вопрос<span class="orange-star">*</span>
                                </label>
                                <div>
                                    <textarea class="form-control" id="{{ form.discussion.id_for_label }}"
                                              name="{{ form.discussion.html_name }}" rows="3"></textarea>
                                </div>
                            </div>


                            <p style="color: orange;font-size: 110%;"> Поля, отмеченные звёздочкой(<span
                                    class="orange-star">*</span>) , являются обязательными.</p>
                            <input type="checkbox" class="custom-checkbox required" id="happy" name="happy" value="yes" required>
                            <label for="happy" style="font-size: 110%;">
                                Отправляя эту форму, вы соглашаетесь с тем, что вы предоставляете KanbanPM свои личные
                                данные
                                , а также с тем, что KanbanPM может выйти с вами на связь по этому вопросу.</label>
                            <div class="form-group mt-4 mb-0">
                                <input class="btn btn-primary btn-block"
                                       style="background-color: #4169E1;font-size:1.1rem;border-color: #4169E1;"
                                       type="submit" value="Отправить " onclick="return validateForm()">
                            </div>
                        </form>
                    </div>

                </div>
            </div>
        </div>
    </div>
</main>
<script>
    function validateForm() {
        var happyCheckbox = document.getElementById('happy');
        var happyError = document.getElementById('happy-error');

        if (!happyCheckbox.checked) {
            happyCheckbox.classList.add('error');
            happyError.style.display = 'block';
            return false;
        } else {
            happyCheckbox.classList.remove('error');
            happyError.style.display = 'none';
            return true;
        }
    }
</script>

{% endblock %}


{% block footer %}
<footer class="py-3 bg-dark">
    <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; 2023</p>
    </div>
</footer>
{% endblock %}

products/templates/products/support.html
{% extends 'products/base.html' %}
{% load static cache humanize %}

{% block css %}
    <link href="{% static 'vendor/css/products.css' %}" rel="stylesheet">

{% endblock %}

{% block content %}
<main>

        <div class="container">
            <div class="fon1"></div>
            <div class="row justify-content-center">
                <div class="col-lg-7">
                    {% if form.errors %}
                        <div class="alert alert-warning alert-dismissible fade show" role="alert"
                             style="margin-top: 50px;">
                            {{ form.errors }}
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                    {% endif %}
                    <div class="card shadow-lg border-0 rounded-lg mt-5">

                        <div class="card-body">
                            <form action="{% url 'products:support' %}" method="post">
                                {% csrf_token %}
                                <div class="form-row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label class="small mb-1" for="{{ form.first_name.id_for_label }}">
                                                Имя
                                            </label>
                                            {{ form.first_name }}
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label class="small mb-1" for="{{ form.last_name.id_for_label }}">
                                                Фамилия
                                            </label>
                                            {{ form.last_name }}
                                        </div>
                                    </div>
                                </div>
                                <div class="form-row">
                                    <div class="col-md-6">
                                        <label class="small mb-1" for="{{ form.username.id_for_label }}">
                                             Адрес электронной почты
                                        </label>
                                        {{ form.username }}
                                    </div>
                                    <div class="col-md-6">
                                        <label class="small mb-1" for="{{ form.email.id_for_label }}">
                                           Телефон
                                        </label>
                                        {{ form.email }}
                                    </div>
                                </div>
                                <div class="form-row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label class="small mb-1" for="{{ form.password1.id_for_label }}">
                                                Страна
                                            </label>
                                            {{ form.password1 }}
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label class="small mb-1" for="{{ form.password2.id_for_label }}">
                                                Задайте ваш вопрос
                                            </label>
                                            {{ form.password2 }}
                                        </div>
</div>
                                </div>
                                 <p style="color: orange;"> Поля, отмеченные звёздочкой (*), являются обязательными.</p>
                                <input type="checkbox" class="custom-checkbox" id="happy" name="happy" value="yes">
                                <label for="happy">
                                Отправляя эту форму, вы соглашаетесь с тем, что вы предоставляете KanbanPM свои личные данные
                                    , а также с тем, что KanbanPM может выйти с вами на связь по этому вопросу.</label>
                                <div class="form-group mt-4 mb-0">
                                    <input class="btn btn-primary btn-block" type="submit" value="Отправить ">
                                </div>
                            </form>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock %}


{% block footer %}
    <footer class="py-5 bg-dark">
        <div class="container">
            <p class="m-0 text-center text-white">Copyright &copy;  2023</p>
        </div>
    </footer>
{% endblock %}